apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sergi
spec:
  rules:
  - host: 34.111.89.89.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-nginx-service
            port:
              number: 80
      - path: /database
        pathType: Prefix
        backend:
          service:
            name: mysql-service
            port:
              number: 3306
